version: "3.5"

services:
  api01: &api
    #image: itujo/rinha-backend-node-uws:latest    
    build: .
    hostname: api01
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=db
      - NODE_ENV="production"
    ports:
      - "3001:3000"
    volumes: 
       - pg-volume:/var/run/postgresql
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "195MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:3000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-volume:/var/run/postgresql
    command: [ "postgres", "-c", "config_file=/docker-entrypoint-initdb.d/postgresql.conf" ]
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"

volumes:
  pg-volume: 

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1